### ISSUE TITLE
secondary navigation in side-nav

### ISSUE THREAD

**Issue by marcopluess** [at-point/mtl#23]
@sled: I started the implementation in 

- https://github.com/at-point/mtl/pull/22
- https://github.com/at-point/cam/pull/561 (for testing over here)

The main idea is to toggle between the ul's, by showing it (could not do that with css only as you could not click through the second element with opacity 0) and toggling the class `compressed` on it.

**Comment by lwe** [comment]
Closing this as _stale_.
