### ISSUE TITLE
Discussion: Message box as a component

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#31]
As we need a message form in several places, it might make sense to add a message box component, containing the following structure: 
![screen shot 2016-07-14 at 14 15 17](https://cloud.githubusercontent.com/assets/3090221/16839083/6d593262-49cd-11e6-9339-ce2b33a834fe.png)

As this is quite restrictive, the actual implementation could be just a simple JS behaviour, to maintain the button disabled as long as no message is provided. 

Open to discussion

**Comment by lgavillet** [comment]
@lwe close or leave?

**Comment by lwe** [comment]
Let's close it 😄
