### ISSUE TITLE
Avatar CSS class conflict

### ISSUE THREAD

**Issue by sled** [at-point/mtl#44]
The MTL helper [`mtl_avatar`](https://github.com/at-point/mtl/blob/master/lib/mtl/rails/view_helpers.rb#L245) and [`mtl_avatar_link`](https://github.com/at-point/mtl/blob/master/lib/mtl/rails/view_helpers.rb#L232) clashes with materialize css [avatar collection item](https://github.com/at-point/mtl/blob/1d2e569474c7355aac42dfa50f2004d318276250/vendor/assets/stylesheets/materialize/_global.scss#L507).

I'd suggest to rename our avatar class [here](https://github.com/at-point/mtl/blob/583a9a4a38a59af5bff5f35b61fdedf74c968c29/app/assets/stylesheets/mtl/extend/_avatars.scss#L7) to something like `mtl-avatar`, `user-avatar`, `avatar-circle` or similar.

**Comment by marcopluess** [comment]
`.mtl-avatar` I'd say

**Comment by marcopluess** [comment]
done
