### ISSUE TITLE
Feature: Fixed headers with flex-box

### ISSUE THREAD

**Issue by sled** [at-point/mtl#55]
The `navbar-fixed` causes some problems due to `position: fixed;`. We could provide an alternative using flex box, i.e the content area stretches from the end of the header to the bottom of the page and is scrollable.

**Comment by marcopluess** [comment]
@sled: can you please specify a screenshot of the problem? and an url by any chance? 

(as far as I am concerned, there is no way we can fix an element with flexbox. so what this would mean a change in the layout? I guess the screenshot will make it a bit more clear)

**Comment by marcopluess** [comment]
@sled ping

**Comment by marcopluess** [comment]
@sled ping 2!

PS: the layout already uses a flexbox, so you could provide the scrolling with a simple overflow param.
<img width="198" alt="screen shot 2016-08-09 at 11 08 57" src="https://cloud.githubusercontent.com/assets/520915/17511043/be5a8162-5e21-11e6-93e7-6d35e087b2e1.png">

But my questions still are:
- On which URL you see the problem?
- In which browser?
- What is the actual problem?

**Comment by marcopluess** [comment]
Tried to solve the issue with your proposed flexbox-n-scroll-layout.. and it's not working. It appears that the script for the scrolling checks on body scroll events only.

![screen shot 2016-08-09 at 12 16 24](https://cloud.githubusercontent.com/assets/520915/17513071/28979a0c-5e2b-11e6-8e46-a688117ab639.png)
![screen shot 2016-08-09 at 12 16 31](https://cloud.githubusercontent.com/assets/520915/17513072/28ccba52-5e2b-11e6-9768-c437d0439cd8.png)

How should we proceed now? Any other ideas/approaches?

**Comment by marcopluess** [comment]
Is there a way we can extend the scripts of table-of-contents to have some sort of offset?

**Comment by marcopluess** [comment]
just for the protocol, this is the reported issue:
[scrolling.mov.zip](https://github.com/at-point/mtl/files/408787/scrolling.mov.zip)

**Comment by lwe** [comment]
Personally I think we should move this on hold and not use any fixed headers at the moment, as there is not directly any support for this in materialize css either.

**Comment by marcopluess** [comment]
@sled: ok for you?

**Comment by marcopluess** [comment]
@sled: ping?
