### ISSUE TITLE
alert messages disrupt the layout

### ISSUE THREAD

**Issue by marcopluess** [at-point/mtl#57]
The notifications used at the moment, disrupt the layout of our backends:
![screen shot 2016-08-09 at 11 55 18](https://cloud.githubusercontent.com/assets/520915/17512541/a1f0ac52-5e28-11e6-99a5-bc54c6d67c26.png)

One way of solving this, would be to put them inside the header:
![screen shot 2016-08-09 at 11 55 47](https://cloud.githubusercontent.com/assets/520915/17512560/ad105efc-5e28-11e6-9a4e-d83195dd9c1f.png) ... from where I could easily optimize the spacings later.

But I don't think that this is the best option. So I wanted to propose something similat to the toasts as a long term solution, but I don't know what the technical implications of this would be:
http://materializecss.com/dialogs.html

Let's have a discussion!

**Comment by lwe** [comment]
This is simply, because the alerts (i.e. Rails flash messages) are rendered at the wrong position, they should be rendered within the form (or maybe yes as a toast with some JS?).

So I propose to close this ticket as invalid / wontfix.

**Comment by sled** [comment]
I think this depends strongly on the context, for validation errors I'd say we should place it above the form itself but this not always possible i.e "XY created successfully", "XY destroyed successfully" which is more a "toasty thing" which you also expect to dissapear while the validation error should stay.

**Comment by lwe** [comment]
We (Simon + me) are considering a `mtl_toast` helper that renders the appropriate JS to show a toast message. This could then be used when rendering the flashes or in any other case (e.g. a partial response).

```haml
# Message directly
= mtl_flash 'Your flash message', duration: 6000, class: 'red'

# Message with some HTML...
= mtl_flash do
  = mtl_icon :cloud, class: 'left'
  This is the cloud!

# Example with Rails flash message
- flash.notice.each do |msg|
  = mtl_flash msg
```

What it would render is some inline JS along the lines of:

```html
<script type="text/javascript">
(function() {
  document.addEventListener('DOMContentLoaded', function(event) {
    var $toast = $("<HTML escaped message>");
    Materialize.toast($toast, duration, class);
  });
}());
</script>
```

**Comment by lwe** [comment]
Closing this in favour of a alternative solution.
