### ISSUE TITLE
Expose the form's label typography as a title

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#61]
In order to display forms as a structured and read-only information, we need to display the form labels as a simple text label. Right now, this typography is only available from within a label, inside a form. The goal is to reuse an existing title tag, like h5 or h6, which is for now not used. 

![screen shot 2016-08-30 at 11 17 02](https://cloud.githubusercontent.com/assets/3090221/18083444/6af3d734-6ea3-11e6-824a-6a53058d306d.png)

🔧  Tasks:
- [x] Define which tag to use: h5 or h6?
- [x] Implement CSS 
- [x] Update corresponding changes/references 

/cc @sled @marcopluess

**Comment by marcopluess** [comment]
done in #62
