### ISSUE TITLE
Form label ellipsing...

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#66]
The form labels currently don't support ellipsing, which can end in a funny looking form: 
![screen shot 2016-09-05 at 13 32 12](https://cloud.githubusercontent.com/assets/3090221/18246617/2cc63f82-736d-11e6-8d60-74b7fb26ded6.png)
As discussed, the idea is to add an ellipsing, if possible, to be safe from failure.

**Comment by marcopluess** [comment]
done here: https://github.com/at-point/mtl/pull/69
