### ISSUE TITLE
File card ellipsing...

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#67]
Right now, the file cards don't support long file names, for example for automated generated names. Example: 
![screen shot 2016-09-05 at 13 31 58](https://cloud.githubusercontent.com/assets/3090221/18246668/711ac6c6-736d-11e6-9d89-83f6a0ea6d62.png)
As discussed, we're more in favour of an ellipsing, rather than a multiline version. This actually tells the user the filename has been shortened. The filename can be fully read using the title tooltip or when displaying the file in preview mode, using the file modals

**Comment by sled** [comment]
@lgavillet Also ran into this problem for the document modals, would be cool if we could ellipsisize like OSX in the middle of the filename to keep the file extension e.g `20160905....0905.pdf` for the file cards we could do this in ruby with the `title` attribute.

**Comment by lgavillet** [comment]
MMmmmh good point. Would be rather in favor of leaving this to the CSS + moreover we have an icon next to it for the extension. But a bit egal for me tbh. @sled Inputs?

**Comment by marcopluess** [comment]
On the css side I'd say we can go as far as `20160905... .pdf`. The OSX way would requiere a quiet complex and dynamic markup. Just FYI

**Comment by sled** [comment]
Double checked and I think we already solved this problem by showing the extension below the filename - this was just a special case without any file extensions (we could still show something like "Unknown"). So it's safe to just ellipsisize on the end i.e "Blabla....."

<img width="490" alt="screen shot 2016-07-15 at 12 13 43" src="https://cloud.githubusercontent.com/assets/98459/16871205/db4cf99e-4a85-11e6-9cbf-0117a91f395c.png">

**Comment by marcopluess** [comment]
as discussed with @sled: no need for css from my side for now.

**Comment by sled** [comment]
<img width="424" alt="screen shot 2016-09-06 at 13 25 49" src="https://cloud.githubusercontent.com/assets/320112/18271986/7686b822-7435-11e6-8366-48ddfda43612.png">

@marcopluess, @lgavillet does this look OK for you?

**Comment by marcopluess** [comment]
@sled: Weltklasse! 🎉

**Comment by sled** [comment]
In case of a title both will be truncated, also OK?

<img width="434" alt="screen shot 2016-09-06 at 13 33 52" src="https://cloud.githubusercontent.com/assets/320112/18272158/940304a4-7436-11e6-818b-0a5d5c4c4b2c.png">

**Comment by lgavillet** [comment]
Perfect

**Comment by marcopluess** [comment]
title ellipsis is fine for me too
