### ISSUE TITLE
simple_form Field Errors

### ISSUE THREAD

**Issue by lwe** [at-point/mtl#72]
MTL should support properly formatting field errors as rendered by the included simple_form settings.

```ruby
    b.use :hint,  wrap_with: { tag: :span, class: 'help-block' }
    b.use :error, wrap_with: { tag: :span, class: 'error-block' }
```

At the moment the markup looks as follows, see trigger `.has-error` and `span.error-block`.

```html
<div class="input-field col s12 string optional has-error">
  <input class="string optional" type="text" value="0" name="abc" id="abc" pattern="\d*">
  <label class="string optional active" for="abc">Label</label>
  <span class="error-block">muss größer als 0 sein</span>
</div>
```

The expected formatting should look like:

<img width="363" alt="screenshot 2016-09-19 11 44 32" src="https://cloud.githubusercontent.com/assets/83660/18628021/763a3c30-7e5e-11e6-83eb-e10d3cb023c6.png">

/cc @lgavillet

**Comment by marcopluess** [comment]
done over here: https://github.com/at-point/mtl/pull/75
