### ISSUE TITLE
Spacing between icon and text

### ISSUE THREAD

**Issue by sled** [at-point/mtl#78]
I often come around the following:

```
<i class="material-icons">some_icon</i>
<span> Some text after the icon</span>
```

At the moment, the text sticks really close to the icon, so I need to either add some spacing by CSS or a `&nbsp;` which is uncool.

What I started to use is something like: 

```
i + span {
  text-indent: 0.5em;
}
```
Should we integrate something like this into MTL?

**Comment by lgavillet** [comment]
```html
<i class="material-icons left">some_icon</i>
<span> Some text after the icon</span>
```
Does by any chance solve this issue? As there's `i.left`, resp. `i.right` css defined with a margin-right/left of 15px to solve this. Or it's too wide? I mean, the more we reuse, the less we add custom global rules, the more maintainable it is, no?

**Comment by lgavillet** [comment]
(yeah, nitpicking a bit)

**Comment by lwe** [comment]
Jup, using `.left` is the trick here basically, would also vote to close it.

**Comment by marcopluess** [comment]
vote for that too!

@sled does this work for you?

**Comment by lwe** [comment]
Has to then 😄 closing this.
