### ISSUE TITLE
Integrate the new header markup

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#94]
Materialize changed the markup for fixed headers and added support for tabs in navbar. Question is now how to integrate a proper DSL for this. Some proposals: 

### Fixed header
http://materializecss.com/navbar.html#navbar-fixed

#### V1
```haml
= mtl_header fixed: true do 
  %p this is a fixed header
```

#### V2
```haml
= mtl_fixed_header do 
  %p this is a fixed header
```

### Extended header (= with tabs)
http://materializecss.com/navbar.html#navbar-tabs

#### V1
```haml
= mtl_header extended: true do 
  = mtl_header_nav do 
    the nav
  = mtl_header_content do 
    %ul.tabs
      %li Abcd
```

#### V2
```haml
= mtl_header_extended do 
  = mtl_header_nav do 
    the nav
  = mtl_header_content do 
    %ul.tabs
      %li Abcd
```

#### V3 
```haml
= mtl_extended_header do |nav|
  = nav.header do 
    the nav
  = nav.content do 
    %ul.tabs
      %li Abcd
```

#### V4 
```haml
= mtl_extended_header do
  = header do 
    the nav
  = content do 
    %ul.tabs
      %li Abcd
```

@philiplehmann @sled @ruinunes inputs?

**Comment by lgavillet** [comment]
PS: just a draft, a mix of the different proposals is obviously doable, all ideas welcome!

**Comment by lgavillet** [comment]
Problem with extended headers is that the block is yielded one level upper, thus not the same behaviour as a classic header.

**Comment by ruinunes** [comment]
(maybe adding to the mix that they do not name these as "header" but "navbar")

**Comment by sled** [comment]
I think we shouldn't burden the user to do this on his own, i.e what about simply:

```
= mtl_header fixed: true do |nav|
  the nav
   = nav.content do
     %ul.tabs 
        %li.tab
end
```

Because we use a builder pattern here, we can "magically" set the `extended` class as soon as the builders `content` method is called.

**Comment by sled** [comment]
imho we also don't save much on this, i.e writing `= nav.content do` vs just `%nav.nav-content` we could directly add support for tabs since this needs a bit more logic, i.e setting `target: _self` etc.

```
= mtl_header fixed: true do |nav|
  the nav
   = nav.tabs do |tabs|
      = tabs.link_to 'Home', home_path
      = tabs.link_to 'Garage', garage_path
   end
end
```

In that case `nav.tabs` first calls `nav.content` and then yields the tabs

**Comment by lgavillet** [comment]
Like the idea! One thing is it doesn't fully respect the HTML markup, which can be misleading... but i assume we could live with that. + some magic to capture the tabs an display them into the correct wrapper. 
```html
 <nav class="nav-extended">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      ...
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        ...
      </ul>
    </div>
  </nav>
```
Another question that pops up with this solution is the tab helper, we don't have one now, would make sense to integrate it too..

**Comment by lgavillet** [comment]
As a first version, something like that works for you ? 
```haml
= mtl_header fixed: true do |nav|
  the nav
   = nav.extended do 
      %somelement
      = anycustomstuffs
   end
end
```
